name: ci

on:
  push:
  pull_request:
    branches: [main]

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-ci
    runs-on: ${{ matrix.os }}-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        name: [windows-msvc]
        buildtype: [Release]
        include:
          - name: windows-msvc
            os: windows
            cxx: cl.exe
            cc: cl.exe

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake with Ninja
        uses: lukka/run-cmake@main
        with:
          configurePreset: 'windows'
          buildPreset: 'windows-release'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-${{ matrix.buildtype }}=${{ github.sha }}
          path: ${{ github.workspace }}/deploy/
